const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const routes={main:{name:'圣巡之旅',codes:Array.from({length:10},(_,i)=>`OS-${i+1}`),time:21},ex:{name:'变革之路',codes:Array.from({length:8},(_,i)=>`OS-EX-${i+1}`),time:54}};
let route='main',stage=0;
function selectStage(i){stage=i;$$('.node').forEach((b,n)=>{b.classList.toggle('active',n===i);b.setAttribute('aria-pressed',n===i)});$('#stage-code').textContent=routes[route].codes[i];$('#stage-type').textContent=routes[route].name;const t=route==='main'&&i>3?38:routes[route].time;$('#stage-time').textContent=`00:${t}`;$('#stage-play').dataset.time=t;$('#stage-copy').textContent=route==='main'?'原片中的圣巡之旅，以相连的关卡节点呈现活动路径。':'原片中的变革之路，以 OS-EX 编号呈现独立的关卡路线。'}
function setRoute(id){route=id;$$('[data-route]').forEach(b=>{const active=b.dataset.route===id;b.setAttribute('aria-selected',active);b.tabIndex=active?0:-1});$('#route-panel').setAttribute('aria-labelledby',`tab-${id}`);$('#route-caption').textContent=routes[id].name+' · 关卡路径';$('#nodes').replaceChildren(...routes[id].codes.map((code,i)=>{const b=document.createElement('button');b.className='node';b.textContent=code;b.onclick=()=>selectStage(i);return b}));selectStage(0)}
$$('[data-route]').forEach(b=>{b.onclick=()=>setRoute(b.dataset.route);b.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();let id=e.key==='Home'?'main':e.key==='End'?'ex':route==='main'?'ex':'main';setRoute(id);$(`#tab-${id}`).focus()}}});$('#ex-link').onclick=()=>setRoute('ex');setRoute('main');
const video=$('#video'),vd=$('#video-dialog');let pendingTime=0;
function openVideo(t){pendingTime=Number(t);vd.showModal();if(video.readyState>=1){video.currentTime=pendingTime;video.play().catch(()=>{})}else{video.load();video.addEventListener('loadedmetadata',()=>{video.currentTime=pendingTime;video.play().catch(()=>{})},{once:true})}}
$$('[data-video]').forEach(b=>b.onclick=()=>openVideo(b.dataset.video));$('#stage-play').onclick=()=>openVideo($('#stage-play').dataset.time);vd.addEventListener('close',()=>video.pause());$$('dialog .close').forEach(b=>b.onclick=()=>b.closest('dialog').close());$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
function info(title,body){$('#info-title').textContent=title;$('#info-body').innerHTML=body;$('#info-dialog').showModal()}
$('#about').onclick=()=>info('关于这份活动档案','<p>本页依据提供的 <strong>SideStory「雪山降临1101」活动.mp4</strong> 制作。影像约 4 分 22 秒，页面图片均取自该视频。</p><p>活动名称、模块名称、关卡编号与「物资支援」说明来自原片。视频内的倒计时及数值属于录制时的历史状态，不代表当前活动状态。</p><p>这里是非官方交互展示；重建操作台使用明确标注的简化演示规则，不接入游戏、不发放奖励。</p>');
$('#rules').onclick=()=>info('重建演示规则','<p>原片「物资支援」显示：点数范围为 <strong>1–5</strong>，每 2 回合随机一片区域的基础资源产出翻倍，所需重建值为 <strong>10</strong>。</p><p>本页为简化演示：选卡后，每回合可收集一次等于点数的矿石与建材；偶数回合随机一种资源翻倍。每投入 3 矿石和 3 建材，增加 1 重建值并进入下一回合。</p><p>达到 10 重建值后完成演示。上述资源消耗和推进方式为网站演示设定，不是原游戏的完整规则。可随时重新开始。</p>');
let dice=3,ore=0,wood=0,score=0,round=1,collected=false;
function renderSim(message){$('#ore').textContent=ore;$('#wood').textContent=wood;$('#score').textContent=score;$('#round').textContent=`第 ${round} 回合`;$('#progress-fill').style.width=`${score*10}%`;$('.progress').setAttribute('aria-valuenow',score);$('#collect').disabled=collected||score>=10;$('#build').disabled=ore<3||wood<3||score>=10;$$('[data-dice]').forEach(b=>{b.disabled=collected||score>=10;b.setAttribute('aria-pressed',Number(b.dataset.dice)===dice);b.classList.toggle('selected',Number(b.dataset.dice)===dice)});if(message)$('#sim-status').textContent=message}
$$('[data-dice]').forEach(b=>b.onclick=()=>{dice=Number(b.dataset.dice);renderSim()});
$('#collect').onclick=()=>{let a=dice,b=dice,bonus='';if(round%2===0){if(Math.random()<.5){a*=2;bonus='本回合矿石翻倍。'}else{b*=2;bonus='本回合建材翻倍。'}}ore+=a;wood+=b;collected=true;if(ore<3||wood<3){round++;collected=false;renderSim(`获得 ${a} 矿石、${b} 建材。${bonus}资源不足，已进入下一回合。`)}else renderSim(`获得 ${a} 矿石、${b} 建材。${bonus}现在可投入重建。`)};
$('#build').onclick=()=>{if(ore<3||wood<3||score>=10)return;ore-=3;wood-=3;score++;round++;collected=false;renderSim(score===10?'重建完成。雪境重新焕发生机！可重新开始体验。':'重建值 +1，进入下一回合。')};
$('#reset').onclick=()=>{dice=3;ore=wood=score=0;round=1;collected=false;renderSim('等待行动。每 2 回合触发一次资源翻倍。')};renderSim();
$$('[data-filter]').forEach(b=>b.onclick=()=>{$$('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b)});$$('.archive-card').forEach(c=>c.hidden=b.dataset.filter!=='all'&&c.dataset.category!==b.dataset.filter)});
const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)$$('nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+e.target.id))})},{rootMargin:'-10% 0px -65% 0px'});$$('main>section[id]').forEach(s=>observer.observe(s));
